# Generated by Django 5.1.6 on 2025-02-23 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('enrolments', models.CharField(max_length=1000)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Assessments',
            fields=[
                ('assessment_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('max_score', models.IntegerField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.courses')),
            ],
        ),
        migrations.CreateModel(
            name='Submissions',
            fields=[
                ('submission_id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('assessment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.assessments')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.users')),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='course_incharge_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.users'),
        ),
    ]
