# Generated by Django 5.1.6 on 2025-02-23 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_remove_users_email_remove_users_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
