# Generated by Django 5.1.6 on 2025-02-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_alter_users_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='LandingPicture',
            field=models.CharField(default='Null', max_length=100),
        ),
    ]
