# Generated by Django 5.1.6 on 2025-02-25 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_courses_landingpicture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessments_Questions',
            fields=[
                ('assessment_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='administration.assessments')),
                ('questions', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Responses',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='administration.users')),
                ('response_data', models.JSONField()),
                ('total_score', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('assessment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.assessments')),
            ],
        ),
    ]
