# Generated by Django 5.1.6 on 2025-02-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_assessments_questions_responses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responses',
            name='assessment_id',
        ),
        migrations.RemoveField(
            model_name='responses',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='assessments',
            name='type',
        ),
        migrations.AddField(
            model_name='assessments',
            name='questions',
            field=models.JSONField(default=None),
        ),
        migrations.AddField(
            model_name='submissions',
            name='response_data',
            field=models.JSONField(default=None),
        ),
        migrations.AlterField(
            model_name='assessments',
            name='max_score',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='score',
            field=models.IntegerField(default=None),
        ),
        migrations.DeleteModel(
            name='Assessments_Questions',
        ),
        migrations.DeleteModel(
            name='Responses',
        ),
    ]
