# Generated by Django 5.1.6 on 2025-02-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_remove_responses_assessment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='resources',
            field=models.JSONField(default=None),
        ),
        migrations.AlterField(
            model_name='users',
            name='enrolments',
            field=models.JSONField(default=None),
        ),
    ]
