# Generated by Django 5.1.6 on 2025-02-25 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_courses_resources_alter_users_enrolments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='resources',
        ),
    ]
