# Generated by Django 5.1.6 on 2025-02-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_remove_courses_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='resources',
            field=models.JSONField(default=None),
        ),
    ]
