# Generated by Django 5.1.6 on 2025-02-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0009_courses_resources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='enrolments',
            field=models.JSONField(default=None, null=True),
        ),
    ]
