# Generated by Django 5.1.6 on 2025-02-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0011_alter_users_enrolments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='enrolments',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
